### ISSUE TITLE
Income the people who rename the client!

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [zzurio/Solaros-Uploading-This-Weekend#1]
!!!!

**Comment by zzurio** [comment]
It's inevitable. 😂

**Comment by Tarkan-Zarrouk** [comment]
😂

**Comment by ghost** [comment]
> It's inevitable. 😂

it finna be like the next oyvey and have over 100 mil ppl rename it constantly

**Comment by M3gaPixel** [comment]
lol

**Comment by 4wl** [comment]
lol

**Comment by Tarkan-Zarrouk** [comment]
> > It's inevitable. 😂
> 
> it finna be like the next oyvey and have over 100 mil ppl rename it constantly

Fr, people finna claim its their code and dont even remove the @author comments LMAO

**Comment by zzurio** [comment]
Lmao

**Comment by zzurio** [comment]
@TwoThreeTwo @notperry12345678902 Posted the src now... everyone will skid the skeet GUI and PanelStudio usage = 📈

**Comment by Tarkan-Zarrouk** [comment]
Already have 33 commits on my profile im skidding too much!!!

**Comment by zzurio** [comment]
Archiving the repo because I am not looking for maintenance on the project. Have fun with the source.
